version: '3.8'
services:
  postgresql:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=gotestbot
    ports:
      - '5432:5432'